### ISSUE TITLE
Missing Gem 'Deface'

### ISSUE THREAD

**Issue by ubergesundheit** [scott/helpy_slack#3]
When I try to run helpy with this gem in the Gemfile, the following error appears:

```
rake aborted!
NameError: uninitialized constant Deface
/usr/local/bundle/bundler/gems/helpy_slack-d3fb15355871/app/overrides/settings.rb:5:in `<top (required)>'
/usr/local/bundle/bundler/gems/helpy_slack-d3fb15355871/lib/helpy_slack/engine.rb:9:in `block in activate'
/usr/local/bundle/bundler/gems/helpy_slack-d3fb15355871/lib/helpy_slack/engine.rb:8:in `glob'
/usr/local/bundle/bundler/gems/helpy_slack-d3fb15355871/lib/helpy_slack/engine.rb:8:in `activate'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:192:in `call'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `each'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/helpy/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

Is it possible, you forgot to specify a gem in the Gemfile?

Cheers,
ubergesundheit

**Comment by scott** [comment]
Yes it is possible I forgot, but first, Did you `bundle install` after adding the gem?

**Comment by scott** [comment]
I just put it in the gem file, although the most recent versions of Helpy have it included which seemed to be all it took for it to work for me.

**Comment by ubergesundheit** [comment]
This ran in docker with the version 0.9.2. I modified the Gemfile of the release (added the `gem 'helpy_slack'...` line) and then just once ran `bundle install`

I will rebuild the image and try again..

**Comment by ubergesundheit** [comment]
Here is what I've done:
`RAILS_ENV` is set to `production`
1. `bundle install`
2. modified Gemfile with `gem "helpy_slack", github: "helpyio/helpy_slack", branch: "master"`
3. `bundle install`
4. `rake assets:precompile`

The error stays the same (`NameError: uninitialized constant Deface`)

Do you think I also need to run `rake deface:precompile`?

I also cannot find the `deface` gem in any of the branches on the main helpy repository..?

**Comment by danblah** [comment]
Finding the same result when deploying to heroku.

**Comment by scott** [comment]
Okay looks like I forgot to require it. If you try it again it should work although you may have to run `bundle update helpy_slack` to flush your cache.

**Comment by ubergesundheit** [comment]
Thanks, trying now!

**Comment by ubergesundheit** [comment]
Seems to work! I haven't tested sending messages to slack but the integration seems to be working.
Thanks!

**Comment by scott** [comment]
Yes please submit another issue if you find problems, i hacked this together pretty quickly and verified it worked with a test room only.
